---
# Deploy OM
- hosts: opsManager
  remote_user: ec2-user
  become: yes
  tasks:
  - template: src=../files/mongodb.repo dest=/etc/yum.repos.d/mongodb.repo owner=root group=root mode="u=rw,g=r,o=r"
  - yum: name=* state=latest
  - yum: name=mongodb-org state=latest
  - yum: name=mongodb-org-shell state=latest
  - yum: name=gpg state=latest
  - file: path=/data state=directory mode=0755 owner=mongod group=mongod
  - file: path=/data/appdb state=directory mode=0755 owner=mongod group=mongod
  - file: path=/data/backup state=directory mode=0755 owner=mongod group=mongod
  - name: Install Cookie Cutter for Python 2.7
    pip:
      name={{ item.name }}
    with_items:
      - name: boto
      - name: boto3
  - name: Launch Mongods for App
    shell: sudo -u mongod mongod --port 27017 --dbpath /data/appdb --logpath /data/appdb/mongodb.log --fork
  - name: Launch Mongods for Backup
    shell: sudo -u mongod mongod --port 27018 --dbpath /data/backup --logpath /data/backup/mongodb.log --fork
# install ops manager
  - copy: src=../files/{{ opsmanager_kit }} dest=/home/ec2-user/{{opsmanager_kit}}
  - yum: name=/home/ec2-user/{{opsmanager_kit}} state=present
  - service: name=mongodb-mms state=started
