- hosts: opsManager
  remote_user: ec2-user
  become: yes
  vars:
    custom_hosts: "{{lookup('file', '../files/customHostnames.txt')}}"
  tasks:
  - name: Change the hostname for OM instance
    hostname:
      name: om.demo
  - name: Update /etc/hosts for OM instance
    shell: echo "{{custom_hosts}}" >> /etc/hosts
  - name: restart machine
    shell: sleep 2 && reboot
    async: 30
    poll: 0
    ignore_errors: true
- hosts: ReplicaSet
  remote_user: ec2-user
  become: yes
  vars:
    custom_hosts: "{{lookup('file', '../files/customHostnames.txt')}}"
  tasks:
  - name: Change the hostnames for Replicas
    hostname:
      name: "{{custom_hostname}}"
  - name: Update /etc/hosts for Replicas
    shell: echo "{{custom_hosts}}" >> /etc/hosts
  - name: restart machine
    shell: sleep 2 && reboot
    async: 30
    poll: 0
    ignore_errors: true
